### ISSUE TITLE
result.

### ISSUE THREAD

**Issue by bourne-3** [orionw/RedditHumorDetection#1]
Hello, your job is very good. But when I re-implement the experimental results, I executed the command line as required, and only got the value of 73.2 f1 score. It does not match the paper, is there a problem?

**Comment by orionw** [comment]
Great question - the results in this repository are slightly higher than the results reported in the paper. This is because my dataset splits were not done with a random seed (due to my inexperience at the time), and thus when I went to make this reproducible (and gave it a random seed), the splits are slightly different than when I evaluated in on the paper.  Since the results are roughly the same, and even better on the new split, I have not updated the paper (the difference between reported and reproducible results is ~0.7%).  I'm sorry for any trouble that may cause! 

If you're comparing against our baseline in an upcoming research paper, I think reporting our results as either of those values would probably be acceptable (though since this data split is easier, I would imagine that a good new model would improve upon the ~73.2 F1 score).

See the notes in https://github.com/orionw/RedditHumorDetection/blob/master/create_data.sh for more details and please let me know if you have any more questions.
