### ISSUE TITLE
code not running

### ISSUE THREAD

**Issue by dominiquebuford** [orionw/RedditHumorDetection#6]
Hi! I've tried to run your code using the 'bash run_bert.sh' command inside a GitHub codespace and the process is being killed and not completing. Is this code no longer able to be run?

**Comment by orionw** [comment]
Hi there!

I have never used a Github codespace but it seems like a server they provide that can run code? BERT-large takes a large amount of VRAM and RAM, so it's possible that your codespace doesn't have the memory capability to run this. It also depends on what your error message was. If it simply said "killed" it probably is RAM and not VRAM issues - either way though you'll need something with enough to run BERT.

Not sure what your situation is, but I would recommend Google Colab if you have that option available. This code should be able to run on the free tier. 

Let me know if you have other questions!

**Comment by LTL235** [comment]
Hi! I have a question, why test.tsv in /data/puns has no labels, while both the train and dev sets have labels

**Comment by orionw** [comment]
The full data is in the `full_dataset` folder and includes all labels. Generally I try to keep the labels off of the test data to avoid accidentally validating on them.  Looks like I only did that with the pun data in this case (not sure why, but this was in 2019 so I've forgotten most of the details now - it also looks like I didn't upload the code I used for splitting that file). However, that doesn't matter since the labels are in the other file.

Feel free to join the data with that in the `full_dataset` folder to get the labels and then evaluate on that.
